language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
  - npm run test && npm run pack